// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SqsRedriveQueueRedriveFunction
 */
export interface SqsRedriveQueueRedriveFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/sqs-redrive.queue-redrive.
 */
export class SqsRedriveQueueRedriveFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SqsRedriveQueueRedriveFunctionProps) {
    super(scope, id, {
      description: 'src/sqs-redrive.queue-redrive.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/sqs-redrive.queue-redrive.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}